
#define _S_1 (S(KC_1))
#define _S_2 (S(KC_2))
#define _S_3 (S(KC_3))
#define _S_4 (S(KC_4))
#define _S_5 (S(KC_5))
#define _S_6 (S(KC_6))
#define _S_7 (S(KC_7))
#define _S_8 (S(KC_8))
#define _S_9 (S(KC_9))
#define _S_0 (S(KC_0))

#define _S_MINS (S(KC_MINS))
#define _S_EQL  (S(KC_EQL))
#define _S_LBRC (S(KC_LBRC))
#define _S_RBRC (S(KC_RBRC))
#define _S_BSLS (S(KC_BSLS))
#define _S_SCLN (S(KC_SCLN))
#define _S_QUOT (S(KC_QUOT))
#define _S_GRV  (S(KC_GRV))
#define _S_SLSH (S(KC_SLSH))
